spring.application.name=resource-booking-system

spring.datasource.url=jdbc:mysql://localhost:3306/resource_booking_db
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

seed.admin.username=${SEED_ADMIN_USERNAME}
seed.admin.password=${SEED_ADMIN_PASSWORD}

seed.user1.username=${SEED_USER1_USERNAME}
seed.user1.password=${SEED_USER1_PASSWORD}

seed.user2.username=${SEED_USER2_USERNAME}
seed.user2.password=${SEED_USER2_PASSWORD}

springdoc.api-docs.enabled=${SWAGGER_ENABLED:false}
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:false}

server.port=8080